---
site_name: Master Mold
site_description: lorem ipsum
site_author: Juan-Pablo Scaletti
site_url: https://github.com/jpscaletti/mastermold

repo_name: jpscaletti/mastermold
repo_url: https://github.com/jpscaletti/mastermold
edit_uri: ""

theme:
  name: material
  custom_dir: material
  logo:
    icon: cloud_done
  palette:
    primary: red
    accent: pink

extra_css:
  - css/monokai.css
  - css/extra.css

# Customization
extra:
  # manifest: "manifest.webmanifest"
  social:
    # - type: globe
    #   link: https://example.com
    - type: github-alt
      link: https://github.com/jpscaletti/mastermold

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
      guess_lang: false
  - smarty
  - toc:
      permalink: "#"
  - markdown.extensions.tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - index.md

# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto
